language: python
python:
  - 3.6
install:
  - pip3 install coveralls


script:
  - coverage  run --omit=exemplos/test*  -m unittest discover -v exemplos
  - -Dsonar.projectKey=lab-python -Dsonar.organization=agileclass -Dsonar.sources=exemplos -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=506dbf36102244307fc8a422efbec1ed5ce4ae85
  - sonar-scanner

  #coverage report -m
  #coverage html


after_success:
  coveralls
    
notifications:
  email:
    recipients:
      - botelhojp@gmail.com
    on_success: change
    on_failure: always