language: python
python:
  - 3.6.4
install:
  - pip install coveralls
script:
  python3.6 -m unittest discover -v test
  
after_success:
  coveralls
    
notifications:
  email: 
    - botelhojp@gmail.com