language: python
python:
  - 3.6
install:
  - pip3 install coveralls
script:
  python3 -m unittest discover -v exemplos

after_success:
  coveralls
    
notifications:
  email: 
    - botelhojp@gmail.com