language: python
python:
  - 3.6
install:
  - pip3 install coveralls
script:
  coverage run -m unittest discover -v exemplos

after_success:
  coveralls
    
notifications:
  email:
    recipients:
      - botelhojp@gmail.com
    on_success: change
    on_failure: always